// Code generated by "stringer -type=Version"; DO NOT EDIT.

package gtasa

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[VERSION_1_00_UNMODIFIED-903512437]
	_ = x[VERSION_1_00_MODIFIED-1710482819]
	_ = x[VERSION_1_01_UNMODIFIED-2590948952]
	_ = x[VERSION_1_01_MODIFIED-2470803038]
	_ = x[VERSION_2_00_UNMODIFIED-4245982710]
	_ = x[VERSION_2_00_GERMAN-1563544610]
	_ = x[VERSION_PS2_V1-1679678540]
}

const (
	_Version_name_0 = "VERSION_1_00_UNMODIFIED"
	_Version_name_1 = "VERSION_2_00_GERMAN"
	_Version_name_2 = "VERSION_PS2_V1"
	_Version_name_3 = "VERSION_1_00_MODIFIED"
	_Version_name_4 = "VERSION_1_01_MODIFIED"
	_Version_name_5 = "VERSION_1_01_UNMODIFIED"
	_Version_name_6 = "VERSION_2_00_UNMODIFIED"
)

func (i Version) String() string {
	switch {
	case i == 903512437:
		return _Version_name_0
	case i == 1563544610:
		return _Version_name_1
	case i == 1679678540:
		return _Version_name_2
	case i == 1710482819:
		return _Version_name_3
	case i == 2470803038:
		return _Version_name_4
	case i == 2590948952:
		return _Version_name_5
	case i == 4245982710:
		return _Version_name_6
	default:
		return "Version(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
